name: iggys_point
description: "iggys_point"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

#  data_table_2: ^2.6.0
#  riverpod: ^2.6.1
  go_router: ^15.2.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
#  dio: ^5.8.0+1
  cloud_firestore: ^5.6.9
  firebase_core: ^3.14.0
  flutter_sticky_header: ^0.8.0
  flutter_screenutil: ^5.9.3
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  fake_cloud_firestore: ^3.0.0
  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:

  uses-material-design: true
  assets:
    - assets/credentials.json
    - assets/players_backup.json
    - assets/player_records_backup.json
